services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: nazanin
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "8080:3306"
    networks:
      - db
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/var/lib/redis

networks:
  db:
    driver: bridge


volumes:
  db_data:
  redis_data: