services:
  db:
    container_name: todo-container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: nazanin
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "8080:3306"
    networks:
      - db

networks:
  db:
    driver: bridge


volumes:
  db_data: