# Generated by Django 5.0.6 on 2024-05-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_board_slug_remove_workspace_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('d', 'Done'), ('w', 'Working on it'), ('p', 'pending')], default='p', max_length=1),
        ),
    ]
