# Generated by Django 5.0.6 on 2024-05-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_expire_at_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expire_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
